In [4]:
print("Hello all!")

Hello all!

In [31]:
import pandas as pd
diabetes_clean = pd.read_csv('diabetes_clean.csv')

print(diabetes_clean)

#diabetes_csv.info()
#diabetes_csv?
#diabetes_csv.describe()
#diabetes_csv.mean()
#diabetes_csv['Unnamed: 2']
#diabetes_csv['Unnamed: 2'].describe()
#diabetes_csv02['Unnamed: 2'][3:]
#diabetes_csv['Unnamed: 2']
#len(diabetes_csv02['Unnamed: 2'][3:])

     diabetes  times_pregnant  glucose_conc  diastolic_BP  triceps_thk  \
0           0               1            85            66           29
1           1               8           183            64            0
2           0               1            89            66           23
3           1               0           137            40           35
4           0               5           116            74            0
..        ...             ...           ...           ...          ...
762         0              10           101            76           48
763         0               2           122            70           27
764         0               5           121            72           23
765         1               1           126            60            0
766         0               1            93            70           31

     2_hr_insulin   bmi  pedigree  age
0               0  26.6     0.351   31
1               0  23.3     0.672   32
2              94  28.1     0.167   21
3             168  43.1     2.288   33
4               0  25.6     0.201   30
..            ...   ...       ...  ...
762           180  32.9     0.171   63
763             0  36.8     0.340   27
764           112  26.2     0.245   30
765             0  30.1     0.349   47
766             0  30.4     0.315   23

[767 rows x 9 columns]

##### Part - 2
- Check if the value for 'glucose_conc' is less than 100.
- Create a new column named 'prediction'.
- If the glucose_conc level is less than 100 then your prediction for that row will be 0 otherwise 1.

In [42]:

#subset = diabetes_clean[diabetes_clean['glucose_conc'] < 100]['glucose_conc']


#diabetes_clean['glucose_conc']
#diabetes_clean['prediction'] = 
#subset

#diabetes_clean['glucose_conc'] < 100
#diabetes_clean['glucose_conc'] = diabetes_clean['glucose_conc'] < 100
#diabetes_clean_02['prediction']
#diabetes_clean_02

pd.apply()




diabetes_clean_02 = diabetes_clean.copy()
diabetes_clean_02['prediction'] = diabetes_clean['glucose_conc'] < 100
diabetes_clean_02

,diabetes,times_pregnant,glucose_conc,diastolic_BP,triceps_thk,2_hr_insulin,bmi,pedigree,age,prediction
0,0,1,85,66,29,0,26.6,0.351,31,True
1,1,8,183,64,0,0,23.3,0.672,32,False
2,0,1,89,66,23,94,28.1,0.167,21,True
3,1,0,137,40,35,168,43.1,2.288,33,False
4,0,5,116,74,0,0,25.6,0.201,30,False
...,...,...,...,...,...,...,...,...,...,...
762,0,10,101,76,48,180,32.9,0.171,63,False
763,0,2,122,70,27,0,36.8,0.340,27,False
764,0,5,121,72,23,112,26.2,0.245,30,False
765,1,1,126,60,0,0,30.1,0.349,47,False
766,0,1,93,70,31,0,30.4,0.315,23,True